//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TFSUri {
            get {
                return ((string)(this["TFSUri"]));
            }
            set {
                this["TFSUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultCollection")]
        public string TFSCollection {
            get {
                return ((string)(this["TFSCollection"]));
            }
            set {
                this["TFSCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDefCreds {
            get {
                return ((bool)(this["UseDefCreds"]));
            }
            set {
                this["UseDefCreds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string User {
            get {
                return ((string)(this["User"]));
            }
            set {
                this["User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Domain {
            get {
                return ((string)(this["Domain"]));
            }
            set {
                this["Domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Activity")]
        public string WIActivity {
            get {
                return ((string)(this["WIActivity"]));
            }
            set {
                this["WIActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Active")]
        public string ActiveState {
            get {
                return ((string)(this["ActiveState"]));
            }
            set {
                this["ActiveState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Deployment</string>
  <string>Design</string>
  <string>Development</string>
  <string>Documentation</string>
  <string>Requirements</string>
  <string>Testing</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ActivityTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ActivityTypes"]));
            }
            set {
                this["ActivityTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastActivityType {
            get {
                return ((string)(this["LastActivityType"]));
            }
            set {
                this["LastActivityType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select [System.Id], [System.Title], [System.State] From WorkItems Where [System.S" +
            "tate] = \'{0}\' AND [System.AssignedTo] = @Me")]
        public string QueryActiveWI {
            get {
                return ((string)(this["QueryActiveWI"]));
            }
            set {
                this["QueryActiveWI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.Title")]
        public string WIFieldTitle {
            get {
                return ((string)(this["WIFieldTitle"]));
            }
            set {
                this["WIFieldTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.AssignedTo")]
        public string WIFieldAssignedTo {
            get {
                return ((string)(this["WIFieldAssignedTo"]));
            }
            set {
                this["WIFieldAssignedTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.TeamProject")]
        public string WIFieldTeamProject {
            get {
                return ((string)(this["WIFieldTeamProject"]));
            }
            set {
                this["WIFieldTeamProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.WorkItemType")]
        public string WIFieldWorkItemType {
            get {
                return ((string)(this["WIFieldWorkItemType"]));
            }
            set {
                this["WIFieldWorkItemType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.VSTS.Scheduling.RemainingWork")]
        public string WIFieldRemainingWork {
            get {
                return ((string)(this["WIFieldRemainingWork"]));
            }
            set {
                this["WIFieldRemainingWork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.VSTS.Scheduling.CompletedWork")]
        public string WIFieldCompletedWork {
            get {
                return ((string)(this["WIFieldCompletedWork"]));
            }
            set {
                this["WIFieldCompletedWork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.VSTS.Common.Discipline")]
        public string WIFieldDiscipline {
            get {
                return ((string)(this["WIFieldDiscipline"]));
            }
            set {
                this["WIFieldDiscipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.VSTS.Scheduling.StartDate")]
        public string WIFieldStartDate {
            get {
                return ((string)(this["WIFieldStartDate"]));
            }
            set {
                this["WIFieldStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft.VSTS.Scheduling.FinishDate")]
        public string WIFieldFinishDate {
            get {
                return ((string)(this["WIFieldFinishDate"]));
            }
            set {
                this["WIFieldFinishDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.LinkTypes.Hierarchy-Reverse")]
        public string WIFieldParentLink {
            get {
                return ((string)(this["WIFieldParentLink"]));
            }
            set {
                this["WIFieldParentLink"] = value;
            }
        }
    }
}
